# Based on VSCode Theme Ariake Dark

# General style
warning = "ariake-warning" # Editor warnings.
error = "ariake-error" # Editor errors, like mis-typing a command. Done
info = "ariake-info" # Contextual info in diagnostic messages (LSP).
hint = "ariake-hint" # Code diagnostics hints (LSP).
diagnostic = "ariake-diagnostic" # Code diagnostics in editing area (LSP). Done

# UI Style
'ui.background' = { } # Default background color. Default for Ariake is fg = "ariake-blue4", bg = "ariake-grey6"
'ui.window' = "ariake-grey2" # Window border between splits.
'ui.gutter' = "ariake-grey2" # Left gutter for diagnostics and breakpoints.

'ui.text' = "ariake-grey1" # Default text color.
'ui.text.focus' = "ariake-purple2" # Selection highlight in buffer-picker or file-picker.
'ui.text.info' = "ariake-grey1" # Info popup contents (space mode menu).

'ui.cursor' = "ariake-white" # Fallback cursor colour, non-primary cursors when there are multiple (shift-c).
'ui.cursor.primary' = { fg = "ariake-grey2", modifiers = ["reversed"] } # The primary cursor when there are multiple (shift-c).
'ui.cursor.insert' = { fg = "ariake-grey2", modifiers = ["reversed"] } # The cursor in insert mode (i).
'ui.cursor.select' = { fg = "ariake-grey3", modifiers = ["reversed"] } # The cursor in select mode (v).
'ui.cursor.match' = { modifiers = ["reversed"] } # The matching parentheses of that under the cursor.

'ui.selection' = { bg = "ariake-grey5", modifiers = ["reversed"] } # All currently selected text.
'ui.selection.primary' = {bg = "ariake-grey5"} # The primary selection when there are multiple.

'ui.linenr' = "ariake-grey2" # Line numbers.
'ui.linenr.selected' = "ariake-grey4" # Current line number.

'ui.statusline.inactive' = "ariake-grey2" # Status line in unfocused windows.

'ui.help' = { fg = "ariake-purple2" } # `:command` descriptions above the command line.

'ui.highlight' = { bg = "ariake-grey5" } # selected contents of symbol pickers (spc-s, spc-S) and current line in buffer picker (spc-b).

'ui.menu' = "ariake-white" # Autocomplete menu.
'ui.menu.selected' = "ariake-purple2" # Selected autocomplete item.

'ui.popup' = "ariake-purple2" # Documentation popups (space-k).
'ui.popup.info' = "ariake-purple2" # Info popups box (space mode menu). Transparent "ariake-purple2"

# Syntax style
'special' = "ariake-grey1" # Special symbols e.g `?` in Rust, `...` in Hare.
'attribute' = "ariake-purple1" # Class attributes, html tag attributes.

'type' = "ariake-purple1" # Variable type, like integer or string, including program defined classes, structs etc..
'type.builtin' = "ariake-string" # Primitive types of the language (string, int, float).

'constructor' = { fg = "ariake-white", modifiers = ["bold"] } # Constructor method for a class or struct.

'constant' = "ariake-purple2"  # Constant value
'constant.builtin' = "ariake-purple3" # Special constants like `true`, `false`, `none`, etc.
'constant.numeric.integer' = "ariake-purple3" # constant integer value.


'string' = "ariake-string" # String literal.
'string.regexp' = "ariake-blue3" # Regular expression literal.

'comment' = "ariake-grey2" # This is a comment.

'variable' = "ariake-blue4" # Variable names.
'variable.builtin' = "ariake-blue4" # Language reserved variables: `this`, `self`, `super`, etc.
'variable.parameter' = "ariake-grey3" # Function parameters.
'variable.other.member' = "ariake-blue4" # Fields of composite data types (e.g. structs, unions).

'label' = "ariake-grey1" # Loop labels, among other things.

'punctuation' = "ariake-grey1" # Any punctuation symbol.
'punctuation.delimiter' = "ariake-grey1" # Commas, colons or other delimiter depending on the language.
'punctuation.bracket' = "ariake-grey1" # Parentheses, angle brackets, etc.

'keyword' = "ariake-purple2" # Language reserved keywords.
'keyword.control' = "ariake-purple2" # Control keywords.
'keyword.control.conditional' = "ariake-purple2" # `if`, `else`, `elif`.
'keyword.control.repeat' = "ariake-purple2" # `for`, `while`, `loop`.
'keyword.control.import' = "ariake-purple2" # `import`, `export` `use`.
'keyword.control.return' = "ariake-purple2" # `return` in most languages.
'keyword.control.exception' = "ariake-purple2" # `try`, `catch`, `raise`/`throw` and related.
'keyword.operator' = "ariake-purple2" # `or`, `and`, `in`.
'keyword.directive' = "ariake-purple2" # Preprocessor directives (#if in C...).
'keyword.function' = "ariake-purple2" # The keyword to define a function: 'def', 'fun', 'fn'.

'operator' = { fg = "ariake-blue3", modifiers = ["bold"] } # Logical, mathematical, and other operators.

'function' = "ariake-purple2"
'function.method' = { fg = "ariake-white", modifiers = ["bold"] } # Class / Struct methods.

'tag' = "ariake-blue2" # As in <body> for html, css tags.
'tag.error' = "ariake-error" # Erroneous closing html tags.

# Markup style
'markup.heading.1' = { fg = "ariake-white", modifiers = ["bold"] } # Markdown heading 1 color.
'markup.heading.2' = { fg = "ariake-white", modifiers = ["bold"] } # Markdown heading 2 color.
'markup.heading.3' = { fg = "ariake-white", modifiers = ["bold"] } # Markdown heading 3 color.
'markup.heading.4' = { fg = "ariake-white", modifiers = ["bold"] } # Markdown heading 4 color.
'markup.heading.5' = { fg = "ariake-white", modifiers = ["bold"] } # Markdown heading 5 color.
'markup.heading.6' = { fg = "ariake-white", modifiers = ["bold"] } # Markdown heading 6 color.
'markup.heading.marker' = { fg = "ariake-white", modifiers = ["bold"] } # Hashtag color on Markdown headings.

'markup.bold' = { fg = "ariake-purple3", modifiers = ["bold"] } # Bold text.
'markup.italic' = { fg = "ariake-purple2", modifiers = ["italic"] } # Italicised text.

'markup.link.url' = "ariake-purple3" # Urls pointed to by links.
'markup.link.label' = "ariake-purple3" # Non-URL link references.
'markup.link.text' = "ariake-blue4" # URL and image descriptions in links.

'markup.quote' = "ariake-purple3" # `> Quotes` in Markdown.

# Diff style 
'diff.plus' = { fg = "ariake-blue4", modifiers = ["bold"] } # Additions.
'diff.minus' = { fg = "ariake-purple2", modifiers = ["bold"]} # Deletions.
'diff.delta' = { fg = "ariake-purple2" } # Modifications.
'diff.delta.moved' = { fg = "ariake-blue4", modifiers = ["italic"] } # Renamed or moved files.

[palette]
ariake-warning = "#dc64fdff" 
ariake-error = "#ff2727ff" 
ariake-info = "#e5e773ff" 
ariake-hint = "#7fe37cff" 
ariake-diagnostic = "#fd0069ff"
ariake-grey1 = "#B9BED5" 
ariake-purple1 = "#A96FED" 
ariake-grey2 = "#666973" #
ariake-purple2 = "#7F7CE3" 
ariake-blue1 = "#59CCFAFF" 
ariake-blue2 = "#73B3E7" 
ariake-blue3 = "#93DDFB" 
ariake-purple3 = "#E89DFC" 
ariake-grey3 = "#555B6EFF" 
ariake-white = "#FAFAFA" 
ariake-blue4 = "#85B1DF" 
ariake-grey4 = "#C6C8CFFF" 
ariake-grey5 = "#686A70FF" 
ariake-grey6 = "#2E323E" 